name: Documentation

on:
  push:
    branches:
      - master
      - actions

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        node-version: 12
    - name: Build documentation
      uses: actions/setup-node@v1
      - run: |
          npm install
          npm run docs
